### PR TITLE
Set COMPOSE_PROJECT_NAME when invoking docker-compose

### PR DESCRIPTION
**Pull request by benjaoming**
Fixes https://github.com/readthedocs/readthedocs.org/issues/9318

### CODE REVIEW

**Comment by benjaoming** [comment]
Reminder to update https://github.com/readthedocs/readthedocs.org/pull/9319 after this is merged

**Review by humitos — CHANGES_REQUESTED** [review]
I commented on https://github.com/readthedocs/readthedocs.org/pull/9319#discussion_r895558715 about how to solve this without introducing this change.

I prefer if we can read this automatically from the `.env` file so we can keep the current setup working together with corporate Docker instances.

**Comment by benjaoming** [comment]
Re:

> I prefer if we can read this automatically from the .env file so we can keep the current setup working together with corporate Docker instances.

I'll make a check to see if it works, but did you notice that the patch does not propose to overwrite existing env variables?

```python
DOCKER_COMPOSE_PROJECT_NAME = os.environ.get('COMPOSE_PROJECT_NAME', 'community')
```

**Comment by humitos** [comment]
Yes. It seems this PR is not required anymore now that #148 got merged.

**Comment by benjaoming** [comment]
The `.env` file does not trump existing environment variables.

I found a segment in the Compose docs that specifices that `.env` can be used _both_ for container instance variables and any other configuration, so I suppose it means that `COMPOSE_PROJECT_NAME` is supposed to be an intentional part of `.env` (I previously read the docs as if it was not intended for comfiguring Compose itself).

> The “.env” file
>
> You can set default values for any environment variables referenced in the Compose file, or used to configure Compose, in an [environment file](https://docs.docker.com/compose/env-file/) named .env. The .env file path is as follows:

**Pull request closed without merging**
