### PR TITLE
pre-commit: tweaks after linting our code

### PR DESCRIPTION
**Pull request by humitos**
Related https://github.com/readthedocs/readthedocs.org/pull/10129

### CODE REVIEW

**Review by benjaoming — APPROVED** [review]
No worries about excluding these :+1: 

Does this mean that `pre-commit run --all-files` works?

**Comment by humitos** [comment]
> Does this mean that `pre-commit run --all-files` works?

Not yet. There are plenty of files that don't pass `prospector`. That will take some extra effort to fix because they are not just quick and simple fixes, but we are getting closer.

**Comment by benjaoming** [comment]
Ah yeah, maybe those complicated things can sit around until we decide what to do with Ruff.

**Comment by humitos** [comment]
I never used it, but I've heard about it and looks promising 😄

**Pull request merged**
